version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: petshop_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: petshop
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: petshop_backend
    restart: always
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/petshop
      SECRET_KEY: 94b7e80d85fc0ac3df145fcd7cf673418579cf4ea1ce75e7a9bbfcd0c3ffbc91
      ALLOWED_ORIGINS: "*"
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: petshop_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data:
